# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63c44852ed52d4575eaa026800afe6bbaeb343190f3888253baa4c573ea301e27b619ed0f41821d439b6f91dfb60f1af109146f7c2e70952ac1ca8eed5189d59

test:
  secret_key_base: 50b4e87e0119a575d42dccda4dcca5f397b13139da28e3520c74c0d1279b8343aadda1b71a7bde6fa29aedccc7de451ce827a4a8ae59a6977c955ba510509004

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
